baseurl = 'https://the-data-philomath.netlify.app/'
title ='The data philomath'
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

# [services]
# [services.disqus]
# shortname = "yourdiscussshortname"

[markup.highlight]
style = "rose-pine-dawn"

[params]
  author = "Nima Sarajpoor"
  info = "An experienced data scientist and machine learning engineer"
  description = "My Personal Website"
  keywords = "blog, data, personal"
  avatarurl = "images/avatar.jpeg"
  # gravatar = "john.doe@example.com"

  # faviconSVG = "/img/favicon.svg"
  # favicon_32 = "/img/favicon-32x32.png"
  # favicon_16 = "/img/favicon-16x16.png"

  math = true

  since = 2025

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

# [taxonomies]
  # category = "categories"
  # series = "series"
  # tag = "tags"
  # author = "authors"

# Social links
[[params.social]]
    name = "Github"
    icon = "fa-brands fa-github fa-2x"
    weight = 1
    url = "https://github.com/NimaSarajpoor"

[[params.social]]
    name = "LinkedIn"
    icon = "fa-brands fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/nimasarajpoor1991/"


# Menu links
[[menu.main]]
name = "About"
weight = 1
url = "about/"

[[menu.main]]
name = "Blog"
weight = 2
url = "posts/"


[[menu.main]]
name = "Achievements"
weight = 3
url = "achievements/"

[[menu.main]]
name = "Publications"
weight = 4
url = "publications/"

[[menu.main]]
name = "Resources"
weight = 5
url = "resources/"

[[menu.main]]
name = "Contact me"
weight = 6
url = "contact/"